### PR TITLE
i18n makefiles and message bundles should be compile-time artifacts

### PR DESCRIPTION
**Pull request by senior**
This PR is intended to start conversation around how this plugin currently works. This patch is against an older version of the codebase (before https://github.com/puppetlabs/clj-i18n/pull/13) . @ajroetker started the patch a couple of weeks ago and I finished it off yesterday. It conflicts pretty bad with that change in PR-13 and before I reworked the patch to accomodate those changes, it seemed like a good time to stop and ask if it's the direction we want to go in for this library.

In talking with @mruzicka, he was under the impression the translators would be working with the Makefiles directly and they wouldn't expect to use Leiningen. This PR would require that. It treats the Makefiles (and message bundles) as and internal detail of the plugin. The Makefile is copied into the target directory (configurable via Lein's :target-path) at compile time and the message bundles are generated and placed into the target/classes directory (configurable via Lein's :compile-path). I also refactored the logic in the i18n plugin into a separate namespace so that it could be invoked from lein before running the tests. This eliminates the need for invoking make out of band before running the tests (currently required).

### CODE REVIEW

**Comment by ajroetker** [comment]
My question related to this PR:

Is there a reason to use `make` at all for this?
Shelling out to the relevant `gettext` commands etc. via Clojure seems much more idiomatic to a lein plugin.
If startup time is what we're worried about, `lein compile` is really fast:
```
lein compile  1.52s user 0.15s system 136% cpu 1.220 total
```
If we're worried about translator folks having to install another tool, I'd probably say that chances are if they have to run these commands they'll most likely have to install lein at some point anyways.

Thoughts?

**Comment by lutter** [comment]
The main reason for using make is indeed startup time; the impact on translators one way or another should be minimal, as developers can always generate the initial `.po` file for them. After that, they depend on (a) that the `.pot` file is updated regularly (ideally on every checkin that changes messages) and (b) importing/exporting their `.po` file via Transifex.

The other reason a Makefile is used is that it is much easier to follow in terms of how files are built, and what they depend on than with custom Clojure code.

But if the consensus is that the Makefile is a major stumbling stone for evolving the library, I am fine with removing it.

**Comment by LarissaLane** [comment]
+1 to @lutter's comment. Translators should never have to interact with any files or tools besides the .po file.

**Comment by senior** [comment]
I think it made things tough for me in two ways. I'm not familiar with make and have never written a Makefile. I think there's one member of the PDB team that has make knowlege to pair with their Clojure knowledge. I also think having two different build systems at play increases the complexity of the build. This PR is mainly focused on making the hand-off between build systems more automatic, shifting that from the person to the code.

I find leiningen plugins pretty easy to write and maintain (i.e. a function in a properly defined namespace), but that could just be that it's more familiar to me.

**Comment by libbymo** [comment]
@lutter @senior @lutter @aperiodic 
Sorry for the bat signal, I'm mainly just pinging all who've expressed some interest in this PR.

I guess the questions I have here are:

1. Does this PR stand on its own? Can we update it, pull it, and then address using lein over make in a ticket, so that we can focus the discussion a bit?  
2. Is updating this PR so complex now that it's not worth it unless other things are decided? If yes, what are those things?
3. Is startup time an issue? I couldn't tell from the comments above. It seems @ajroetker implies it's not. I frankly, don't know.
4. There's a conversation around .pot files, and how translators most likely won't be dealing with anything but a .po file already in transifex.  So whether it's lein or make - seems a non-issue, unless I'm misunderstanding.  I will make sure to verify this.

Just want to keep this going, or close it - you did some serious work here and I don't want it to languish out of neglect. I'd rather a decision just be made and we address it or close it.

My two cents as well, I'd like to get this in place, in that I like the idea of not having an out of date makefile.  We currently have an out of date makefile in classifier, as we bumped the version, and didn't run init again.  It'd be nice if it were no longer an issue. I think in and of itself has value.  And the next step of using lein, seems a separate discussion - which has merit.  I just think bit by bit.

**Comment by senior** [comment]
> 1. Does this PR stand on its own? Can we update it, pull it, and then address using lein over make in a ticket, so that we can focus the discussion a bit?

We could spend the time needed to get the PR rebased, but I think the question in my mind is what's the most efficient use of our time. I submitted the PR as-is because @ajroetker and I put a decent amount of time into already and wasn't sure this was a change that we wanted. Rather than pour more time into it, I figured I'd start the conversation.  If we had to wait a month before we were able to get a pure lein version of this plugin, would that be ok? Since this stuff isn't going to be used until January+, seems like we have some timing flexibilty

> 2. Is updating this PR so complex now that it's not worth it unless other things are decided? If yes, what are those things?

If we wanted to go with lein, seems like there's more value in working on that than rebasing this. There's not just the ~3 hours to rework/merge with what's there. Each project will have to update the dep, remove their Makefile, change gitignore etc. I'm not sure if those users would have to make similar adjustments once a lein solution is in place.  @ajroetker any rough ideas on effort for writing a lein plugin to do this?

> 3. Is startup time an issue? I couldn't tell from the comments above. It seems @ajroetker implies it's not. I frankly, don't know.

@ajroetker and I don't have as much background on the users of this and the key factors going into the Makefile decision. I agree with AJ though, startup time isn't a big deal for me.

> 4. There's a conversation around .pot files, and how translators most likely won't be dealing with anything but a .po file already in transifex. So whether it's lein or make - seems a non-issue, unless I'm misunderstanding. I will make sure to verify this.

If we can agree on this, sounds like we can have the make/lein discussion focusing just on devs and tech.

**Comment by senior** [comment]
@lutter @aperiodic @libbymo bump

**Comment by libbymo** [comment]
I'm sorry it took me so long to respond, I had to verify what pieces in the steps were still missing - that directly affected this library. 

@lutter correct me if I'm wrong on this.  But we had some conclusions around how the i18n flow would work.  It was decided that we would remove the makefile entirely and replace it with a CI script, responsible for generating the .pot/po files - this CI job would commit the .po files.  We will probably need to get rid of the makefile altogether and move the parts (msgfmt) that generate the resource bundles from the PO files into the lein plugin to be triggered on lein compile. I'm unsure exactly how this should work.  But this was what was proposed.

@lutter I believe that means we can close this PR.

**Comment by lutter** [comment]
I agree that we should hold off on doing more work on this PR until we have the CI story straightened out. Once we have CI reliably update .pot/.po files, there shouldn't be much of a developer impact anymore and much less of a need for devs to update these files.

I would still want to have some way for devs to update .pot/.po files locally but since that would be used very infrequently, it would be enough if devs could run the scripts that are used in CI manually.

**Comment by senior** [comment]
:+1:

**Comment by cprice404** [comment]
Where did we land on this?  I am just now starting to spend some quality time with this stuff, and I agree with @senior .  Besides the dev-env vs. CI build time questions, I also feel like it's very unusual and a little risky for the plugin to be putting files into the `resources` dir and asking devs to use .gitignores on that directory, so I'd love to see this get resuscitated so that those kinds of steps aren't necessary...

**Pull request closed without merging**
